### ISSUE TITLE
Creating one Vat for a service that requires a client capability for the initialisation of the server

### ISSUE THREAD

**Issue by nickbetteridge** [mirage/capnp-rpc#136]
Firstly, an excellent tutorial.
Currently working my way through and have an issue with Vat's. I would like to serve a Vat which needs to import a client capability for the initialisation of the server. Consider the server:
```
let serve config client_capability =
Lwt_main.run begin
    let service_id = Capnp_rpc_unix.Vat_config.derived_id config "main" in
    let restore = Restorer.single service_id (Http_server.local client_capability) in
    Capnp_rpc_unix.serve config ~restore >>= fun vat ->
    let uri = Capnp_rpc_unix.Vat.sturdy_uri vat service_id in
    Fmt.pr "echo service running at: %a@." Uri.pp_hum uri;
    fst @@ Lwt.wait ()  (* Wait forever *)
  end
```
The client_capability has already been created with:
```
let start_server server_config store_uri =
  ....
    Fmt.pr "Connecting to echo service at: %a@." Uri.pp_hum uri;
    let client_vat = Capnp_rpc_unix.client_only_vat () in
    let sr = Capnp_rpc_unix.Vat.import_exn client_vat store_uri in
    Sturdy_ref.connect_exn sr >>= fun client_capability ->
    serve server_config client_capability
```
The client capability (client_capability) has already been created by creating another client_only_vat as the server vat is only created after the client capability has been created. Reading through capnp_rpc_unix.ml I can see how to do a little hacking and ensure I just create one Vat.
This is all coming on the back of the https_unikernel example where I need to pass in the remote store capability to the http_server handler.
I guess what I'm asking is - would I be better served (yes,pun) by creating the store capability dynamically (already tried this and it gets hairy) or should I just stick to doing my own vat creation?

**Comment by talex5** [comment]
I'm not sure I understand the question. Except for testing, each process should only create one vat.

The https example has three vats (because it runs as three Unix processes):

    HTTPS     vat         capnp      vat     capnp   vat
    ----> tls_terminator  ---->  http_server -----> store

`http_server` acts as a client to `store` but as a server to `tls_terminator`, so referring to things as "the server" here is ambiguous (there are two capnp servers and one https server).

You will need to wait for `store` to start up and generate its key before you can start `http_server` (although you could generate the keys ahead of time if you wanted to automate the initial deployment).

**Comment by nickbetteridge** [comment]
My problem is that to create the store proxy - for the http_server's callback - you need a vat, and this is only created once ```Capnp_rpc_unix.serve``` is serving.

This is your Http_Server.local:
```
let local store =
  let handle_http_connection = Server.callback (Server.make ~callback:(handle_request store) ()) in
  Rpc.Http.local (fun flow ->
      Log.info (fun f -> f "Handing new connection");
      handle_http_connection flow (Remote_flow_unix.ic flow) (Remote_flow_unix.oc flow) >>= fun () ->
      Capability.dec_ref flow;
      Lwt.return_unit
)
```
and this what I'm trying to achieve:
```
let serve store_uri http_config =
  Lwt_main.run begin
    let service_id = Capnp_rpc_unix.Vat_config.derived_id http_config "http_main" in

    let vat = Capnp_rpc_unix.create_serve_vat http_config ~restore in

    let store_sturdy_reference = Capnp_rpc_unix.Vat.import_exn vat store_uri in
    Sturdy_ref.connect_exn store_sturdy_ref >>= fun store_capability ->
    Http_server.local store_capability >>= fun store ->

    let restore = Restorer.single service_id store in

    Capnp_rpc_unix.serve_vat ~restore http_config vat >>= fun vat ->
    let uri = Capnp_rpc_unix.Vat.sturdy_uri vat service_id in
    Fmt.pr "http_main service running at: %a@." Uri.pp_hum uri;
    fst @@ Lwt.wait ()  (* Wait forever *)
  end
```
```Capnp_rpc_unix.create_serve_vat``` is the initial part of the exising ```Capnp_rpc_unix.serve``` and ```Capnp_rpc_unix.serve_vat``` is the bulk of ```Capnp_rpc_unix.serve```.

**Comment by talex5** [comment]
Ah, I see: you can't import the store's URI into the vat until the vat has been created, and you can't create the vat until the http server is available, but the http server needs the imported store.

There are two ways you could solve this:

1. Start the vat with an empty restorer (using `Restorer.of_table`), and then add the http service afterwards. This does mean there will be a small window when your server is available but claims the http service doesn't exist.

2. Create the http server using a promise for the store rather than the store itself, and then resolve the promise as soon as you have it.

e.g.

```
let store_promise, resolver = Lwt.wait () in
Http_server.local store_promise >>= fun http_service ->
let restore = Restorer.single service_id http_service in
...
Lwt.wakeup resolver store_sturdy_reference
```

Then your http server will be available immediately, but if a request comes in before the store proxy is ready, it will just wait a bit.

(note: you probably want to pass the sturdy ref rather than the proxy, so that the http server can reconnect if there is a network problem)

**Comment by nickbetteridge** [comment]
Thanks for the fast response to my issue - apols for the delay in replying - just spent 2 days trying to set up cohttp+promise efficiently - failed, more than likely due to my skills with lwt. Just  switched over to using ```Restorer.Table``` and it works perfectly. Would you like me to add this example to capnp-rpc?

**Comment by talex5** [comment]
Good to hear it's working for you.

Thanks for the offer, but I'd prefer to keep the current docs, as in some cases the race at start-up could be a problem. Turning the promise into a sturdy ref should just be a case of doing `store_promise >>= fun store ->` when you need to use it (and note that you can't use it as part of the initialisation code, because it won't resolve until that returns).

There should probably be some kind of helper to simplify this, returning the current live capability as long as it's not broken, or getting a new one from the sturdy ref (promise) if it is.
