### ISSUE TITLE
[Question] dec_ref on an interface

### ISSUE THREAD

**Issue by sidkshatriya** [mirage/capnp-rpc#258]
Thank you for this library. It seems to be one of the few more fleshed out capnp-rpc implementations out there (apart from the reference C++ one). The examples are wonderfully written, the code looks exceedingly clean, ...

One thing that keeps confusing me is the `inc_ref` and `dec_ref` as far as capabilities are concerned. It confusing to me when we need to do that and there seem to be some subtleties here e.g. see the `calc.ml` example especially the `release` function.

Maybe I haven't understood the concept very well yet. 

> But the simple rule is: any time you create a local capability or extract a capability from a message, you must eventually call Capability.dec_ref on it.

What does "eventually" mean and when does it happen? 

What exactly does it even mean to maintain a reference to a capability in the context of capnp-rpc ? Is it even possible to do this automatically and not have to have to involve the user? One of the strong points of OCaml is the garbage collector -- is it possible to just ride on it? 

Some more clarity on this in the documentation would be very welcome !

**Comment by sidkshatriya** [comment]
Also when does a Capability get duplicated or copied in OCaml? When you pass it as an argument to another function for example? In other words when does the count get incremented?

**Comment by talex5** [comment]
> What does "eventually" mean and when does it happen?

If the GC gets to it before you do, it will log a warning. So you have to release it (reduce the ref-count to zero) before dropping the last reference to it.

> What exactly does it even mean to maintain a reference to a capability in the context of capnp-rpc?

It means that the remote site knows you're still using it and can't free the resource (though everything will get released if the TCP connection ends).

> One of the strong points of OCaml is the garbage collector -- is it possible to just ride on it?

In general, no, because you'd need a distributed garbage collector that followed references over the network to detect cycles between machines. Also, the GC runs when the local machine wants to reclaim memory, but it would need to run when the remote machine wants to free things too.

For another example, OCluster will cancel a job when its ref-count reaches zero. If you rely on GC, it might continue building things that are no longer needed.

**Comment by sidkshatriya** [comment]
Thank you for patiently explaining. So when you do a `dec_ref` on a capability, capnp reaches out on the network and says to the other endpoint that it does not need the resource represented by that capability?

**Comment by talex5** [comment]
Yes, once the ref-count reaches 0, it notifies the other endpoint.

**Comment by sidkshatriya** [comment]
Great -- that was the main issue with my understanding -- the fact that a `dec_ref` will be a network operation when the count reaches 0. That is something I didn't realise. 

I thought these references represented some internal book keeping only -- but as you explained, it is not. This makes much more sense now. Thanks!
